export * from "./login";
export * from "./getRestaurants";
export * from "./addRestaurant";
export * from "./getCategories";
export * from "./editRestaurant";
export * from "./deleteRestaurant";
export * from "./deleteCategory";
export * from "./addCategory";
export * from "./addAdmin";
export * from "./getAdmins";
export * from "./deleteAdmin";
export * from "./editAdmin";
export * from "./getDeliveries";
export * from "./addDeliveryUser";
export * from "./deleteDeliveryUser";
export * from "./editDeliveryUser";
export * from "./editCategory";
export * from "./updateAdminRoles";
export * from "./getAllProducts";
export * from "./deleteProduct";
export * from "./editProduct";
export * from "./createProduct";
export * from "./getProductById";
export * from "./deleteProductImage";
export * from "./addDeliveryCostForVendor";
export * from "./getDeliveryAreas";
export * from "./deleteRestauarantAreaCost";
export * from "./editDeliveryCost";
export * from "./deleteDeliveryArea";
export * from "./addDeliveryArea";
export * from './editDeliveryArea'
export * from './deleteProductOptionById'
export * from './deleteOptionsGroupById'
export * from './addProductGroupOption'
export * from './editProductOption'
export * from './editProductGroup'
export * from './getSliderData'
export * from './deleteSlider'