export const getAllRestaurants = 'vendor/get-vendors'
export const addRestaurant = 'vendor/create-vendor'
export const editRestaurant = 'vendor/edit-vendor'
export const getDeliveriesUsers = 'delivery/get-deliveries'
export const addDeliveryUser = 'delivery/create-delivery'