export * from "./button";
export * from "./form";
export * from "./input";
export * from "./label";
export * from "./spinner";
export * from "./scroll-area";
export * from "./SideBar";
export * from "./dropdown-menu";
export * from "./checkbox";
export * from "./alert-dialog";
export * from "./DeleteRestuarantDialog";
export * from "./dialog";
export * from "./select";
import { RestaurantsTable } from "./RestaurantsTable";
export { RestaurantsTable };
